name: Build package

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          # - humble
          - jazzy
          - rolling
        include:
          # - ros_distribution: humble
          #   ubuntu_version: noble
          - ros_distribution: jazzy
            ubuntu_version: noble
          - ros_distribution: rolling
            ubuntu_version: noble
            
    container:
      image: ubuntu:${{ matrix.ubuntu_version }}
      
    steps:
    - name: Update git
      run: |
        apt-get update
        apt-get install -y git

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
        
    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y \
          python3-colcon-common-extensions \
          python3-rosdep \
          libboost-dev \
          libxml2-dev
          
    - name: Build
      run: |
        . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
        colcon build --event-handlers console_direct+
        